name: Dependencies

on:
  workflow_dispatch:
# permissions: 
#   contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
         egress-policy: audit
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt
